server:
  port: 8081
app:
  topic: demo-topic
  queues:
    main: demo-queue
    dlq: demo-queue.dlq
    error: demo-queue.error
  retry:
    max-attempts: 3
    delay-ms: 2000

spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
        group-id: demo-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#spring:
#  kafka:
#    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    consumer:
#      group-id: demo-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
