services:
  procpag:
    image: docker.io/erickemprobr/procpag:latest 
    platform: linux/amd64
    ports: 
    - "8089:8089"
    networks:
    - fase3net

  # adicione os seus outros serviços aqui
  # faça com que todos os serviços usem a mesma rede 'fase3net'

networks:
  fase3net:
